[build]
  # Build command for Next.js static export
  command = "npm run build"
  # Output directory for static files
  publish = "out"

# Redirect all API calls to your backend (you'll need to deploy backend separately)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# Redirect chatbot API
[[redirects]]
  from = "/chatbot"
  to = "https://your-backend-url.com/chatbot"
  status = 200
  force = true

# Redirect tickets API
[[redirects]]
  from = "/tickets/*"
  to = "https://your-backend-url.com/tickets/:splat"
  status = 200
  force = true

# Redirect KB API
[[redirects]]
  from = "/kb/*"
  to = "https://your-backend-url.com/kb/:splat"
  status = 200
  force = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Next.js environment variables
  NEXT_PUBLIC_API_URL = "https://your-backend-url.com"
  NODE_VERSION = "18"
