services:
  # FastAPI Backend Service
  - type: web
    name: powergrid-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: ENVIRONMENT
        value: production
      # Database - You need to add these values
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      # Email Configuration
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: CHATBOT_FROM
        sync: false
      # SMS Configuration (Twilio)
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  # PostgreSQL Database (Optional - if you want Render to host DB)
  - name: powergrid-db
    databaseName: powergrid_tickets
    user: powergrid_user
    plan: free
    region: oregon
